### ISSUE TITLE
cant find links

### ISSUE THREAD

**Issue by gg2187** [crashworks3d/Iron_Man_Servo#26]
hello, in franklybuilts video on how to do this project, under prerequisite, there are a few more links to other githubs with code, but they are no longer there. Is there another spot to find it? thanks!

**Comment by i3creations** [comment]
Frank's YouTube video is outdated.  See: https://github.com/crashworks3d/Iron_Man_Servo/blob/v3.0.1.2/UPLOAD_CODE.md
