### ISSUE TITLE
Unable to get working without dual power supplies

### ISSUE THREAD

**Issue by mminella** [crashworks3d/Iron_Man_Servo#28]
I currently have this wired up on a breadboard based on the wiring diagram provided. However, I'm running into an issue. 

If I use my breadboard power supply with no USB connected to the Nano, the power light on the Nano does not come on unless I press the button. If I connect the micro USB to the Nano and don't use the breadboard power supply, I get a consistent power light but pressing the button doesn't do anything (I'm assuming because there aren't enough amps coming through). The only way I can get things to work is if I have _both_ the breadboard power supply and the micro USB connected.  Then things seem to work fine.

The breadboard power supply I'm using is an HW-131. I've tried running it with either USB (from a laptop or this power bank: https://www.amazon.com/Portable-10000mAh-External-Compatible-Cellphones/dp/B07P11H8PT?th=1) or a corded adapter.

What am I missing? Thanks in advance!

**Comment by i3creations** [comment]
Hi! The best place to ask questions and get help is through the community of makers on Frankly Built’s free discord: https://discord.com/invite/franklybuilt.   We have an #electronics-forum and #crashworks3d-questions channel. See you there!
