### ISSUE TITLE
Can you (or I) make it work on Nano Every?

### ISSUE THREAD

**Issue by ElkHeart4Dinner** [crashworks3d/Iron_Man_Servo#32]
I have an Arduino Nano Every instead of a regular Arduino Nano. I'm new to Arduino. Is there any way to easily make this code run on the Nano Every board instead?

**Comment by mcrandall-cvp** [comment]
Yes.  Use this branch instead: https://github.com/crashworks3d/Iron_Man_Servo/tree/v3.2.x

**Comment by i3creations** [comment]
Yes, use this branch: https://github.com/crashworks3d/Iron_Man_Servo/tree/v3.2.x
