### ISSUE TITLE
Arduino Nano every

### ISSUE THREAD

**Issue by HansGruber01** [crashworks3d/Iron_Man_Servo#35]
Uploaded the code the nano every and when push the push button the LED eyes just dim and brighten. the servos dont move

**Comment by Siphon216** [comment]
I am having the exact same issue.

I loaded the code to the nano and the components have been wired as per the instructions. Once servos and LED eyes have finished the startup (initializing flickering LED event), I am able to control only the dimming feature (press and hold) with the button. Single and double button presses do not work to control the faceplate servos. I've also noticed that there is no TX LED idicator when the single or double button action is pressed. The TX LED indicator does flash when the press and hold dimming feature is in action.

**Comment by i3creations** [comment]
Likely you wired your button wrong.
