### ISSUE TITLE
Servos not responding

### ISSUE THREAD

**Issue by SavageYeye** [crashworks3d/Iron_Man_Servo#7]

**Comment by crashworks3d** [comment]
What is the issue ? 

Are you using the correct type of Arduino, our code will not work on an Arduino Nano "Every", it only works on a standard Arduino Nano with the ATMega328p processor.

What are you powering your circuit with ? You should be using a 5v (2.1A) Power bank.

What type of switch are you using ?   It must be a momentary "Normally-Open" (NO) type switch, it cannot be a "Normally-Closed"(NC) type switch.

Are you using MG90S (180 degree) servos ? MG90s (360 degree) will not work correctly.

Do you have a picture of your wiring ?

Best thing is to join Frankly Built's discord and troubleshoot with the community there:
https://discord.gg/cxzDpfM

**Comment by crashworks3d** [comment]
No details provided.
