### ISSUE TITLE
Servo.write command.

### ISSUE THREAD

**Issue by jjorkfrit** [crashworks3d/Iron_Man_Servo#8]
I've been having problems compiling the code for the helmet. Every time I compile it I get the following error message...

In file included from C:\Users\jjork\Documents\Arduino\Iron_Man_Helmet_MK3_1.1\Iron_Man_Helmet_MK3_1.1.ino:45:0:
C:\Users\jjork\Documents\Arduino\libraries\VarSpeedServo/VarSpeedServo.h:130:8: note: candidate: void VarSpeedServo::write(int)
   void write(int value);             // if value is < 200 its treated as an angle, otherwise as pulse width in microseconds
        ^~~~~
C:\Users\jjork\Documents\Arduino\libraries\VarSpeedServo/VarSpeedServo.h:130:8: note:   candidate expects 1 argument, 2 provided
exit status 1
no matching function for call to 'VarSpeedServo::write(const int&, const int&)'

I have everything else in working order except the line with servo1.write(servo1_closePos, servoCloseSpeed); however, it is for servos 1 and 2 for opening and closing. I am not sure if this is just a me problem or not. get back to me with any advice. thanks :)

**Comment by i3creations** [comment]
The most common issue is that you are trying to compile the code for a board that is not supported such as the Nano Every.

**Comment by jjorkfrit** [comment]
its set to Arduino nano with the most recent bootloader and it is still having the same issue
