### ISSUE TITLE
ESP32

### ISSUE THREAD

**Issue by flow1990** [crashworks3d/Iron_Man_Servo#9]
Sorry but I do not really understand which Arduino I need for this. Would this work with an ESP32? I mean normally I would just use the code and make my own version (I want it to subscribe to an MQTT topic) but since you wrote „ If you have an AM2, AM3 or AM4 board, DO NOT USE THIS CODE!!!“ I am a bit confused.

**Comment by i3creations** [comment]
The code was designed to work with the Arduino Nano ATMega328P architecture.  You will get compile errors with an ESP32.
